PUT http://localhost:3001/api/users/645b3ee5b809e2e3438822f7
Content-Type: application/json

{
"name":"Late",
"username":"laurisakari",
"boulderFlashGrade":"8A",
"sportFlashGrade":"6B+",
"climbedRoutes":
  [
   {"grade":"6A",
    "boulder":53,
    "sport":43},
    {"grade":"6A+",
    "boulder":54,
    "sport":42},
    {"grade":"6B",
    "boulder":48,
    "sport":48},
    {"grade":"6B+",
    "boulder":24,
    "sport":24},
    {"grade":"6C",
    "boulder":12,
    "sport":12},
    {"grade":"6C+",
    "boulder":6,
    "sport":6},
    {"grade":"7A",
    "boulder":3,
    "sport":3},
    {"grade":"7A+",
    "boulder":1,
    "sport":1}
    ],
    "id":"645b3ee5b809e2e3438822f7"}